# Generated by Django 3.0.5 on 2020-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=180),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
